<h1> Laptop Pricing Dataset Cleaning with Data Analysis Techniques </h1>

# Objectives

After completing this lab you will be able to:

 - Handle missing data in different ways
 - Correct the data type of different data values as per requirement
 - Standardize and normalize the appropriate data attributes
 - Visualize the data as grouped bar graph using Binning
 - Cnverting a categorical data into numerical indicator variables

In [2]:
## import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import requests

In [3]:

#download the dataset

def download(url, fileName):
    response = requests.get(url)
    if(response.status_code == 200):
        with open(fileName, "wb") as f:
            f.write(response.content)

In [4]:
file_path= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DA0101EN-Coursera/laptop_pricing_dataset_mod1.csv"

In [5]:
download(file_path, "laptops.csv")
file_name = "laptops.csv"

In [6]:
# we are going to create a datafram as df using the laptops.csv

df = pd.read_csv(file_name)
df.head()

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837

In [9]:
#we get the summary about dataset
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 238 entries, 0 to 237
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Unnamed: 0      238 non-null    int64
 1   Manufacturer    238 non-null    str
 2   Category        238 non-null    int64
 3   Screen          238 non-null    str
 4   GPU             238 non-null    int64
 5   OS              238 non-null    int64
 6   CPU_core        238 non-null    int64
 7   Screen_Size_cm  234 non-null    float64
 8   CPU_frequency   238 non-null    float64
 9   RAM_GB          238 non-null    int64
 10  Storage_GB_SSD  238 non-null    int64
 11  Weight_kg       233 non-null    float64
 12  Price           238 non-null    int64
dtypes: float64(3), int64(8), str(2)
memory usage: 24.3 KB

In [12]:
## rounded the column screensize cm to nearest two decimal places.
## consider as a dataframe

df[['Screen_Size_cm']] = df[['Screen_Size_cm']].astype("float")
df[['Screen_Size_cm']] = np.round(df[['Screen_Size_cm']], 2)
df['Screen_Size_cm'].head()

0    35.56
1    39.62
2    39.62
3    33.78
4    39.62
Name: Screen_Size_cm, dtype: float64

# Task 1: Finding Missing Values

<p> Evaluate the data set for missing data </p>

In [14]:
df.isnull().sum()

Unnamed: 0        0
Manufacturer      0
Category          0
Screen            0
GPU               0
OS                0
CPU_core          0
Screen_Size_cm    4
CPU_frequency     0
RAM_GB            0
Storage_GB_SSD    0
Weight_kg         5
Price             0
dtype: int64

In [18]:
## Alnternate way
missing_data = df.isnull()
print(missing_data.head())

for colum in missing_data.columns.values.tolist():
    print(missing_data[colum].value_counts())
    print("")

   Unnamed: 0  Manufacturer  Category  Screen    GPU     OS  CPU_core  \
0       False         False     False   False  False  False     False
1       False         False     False   False  False  False     False
2       False         False     False   False  False  False     False
3       False         False     False   False  False  False     False
4       False         False     False   False  False  False     False

   Screen_Size_cm  CPU_frequency  RAM_GB  Storage_GB_SSD  Weight_kg  Price
0           False          False   False           False      False  False
1           False          False   False           False      False  False
2           False          False   False           False      False  False
3           False          False   False           False      False  False
4           False          False   False           False      False  False
Unnamed: 0
False    238
Name: count, dtype: int64

Manufacturer
False    238
Name: count, dtype: int64

Category
False    238
Name: count, dtype: int64

Screen
False    238
Name: count, dtype: int64

GPU
False    238
Name: count, dtype: int64

OS
False    238
Name: count, dtype: int64

CPU_core
False    238
Name: count, dtype: int64

Screen_Size_cm
False    234
True       4
Name: count, dtype: int64

CPU_frequency
False    238
Name: count, dtype: int64

RAM_GB
False    238
Name: count, dtype: int64

Storage_GB_SSD
False    238
Name: count, dtype: int64

Weight_kg
False    233
True       5
Name: count, dtype: int64

Price
False    238
Name: count, dtype: int64

## Task 2: Replace with Mean
 <p> weight can be replace with the mean of the column data </p>

In [19]:
df['Weight_kg'].dtype

dtype('float64')

In [24]:
mean_weights = np.round(df['Weight_kg'].mean(axis=0), 2)
print("Mean of weight_kg column: " , mean_weights)

Mean of weight_kg column:  1.86

In [ ]:
df['Weight_kg'] = df['Weight_kg'].fillna(mean_weights)
print(df['Weight_kg'].head())

df['Weight_kg'].isnull().sum()

0    1.60
1    2.20
2    2.20
3    1.22
4    1.91
Name: Weight_kg, dtype: float64

### Replace with the most frequent value
Missing values in attributes that have categorical data are best replaced using the most frequent value. We note that values in "Screen_Size_cm" attribute are categorical in nature, and some values are missing. Therefore, write a code to replace the missing values of Screen Size with the most frequent value of the attribute.

In [40]:
df.head()

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.56,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.62,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.62,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.78,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.62,1.8,8,256,1.91,837

In [44]:
df['Screen'].value_counts()

Screen
Full HD      161
IPS Panel     77
Name: count, dtype: int64

In [62]:
#maxium value use for screen 
commonvalue =df['Screen'].value_counts().idxmax()

In [66]:
#replace null values of screen with Full HD
common_screen_size = df['Screen_Size_cm'].value_counts().idxmax()
df["Screen_Size_cm"] = df["Screen_Size_cm"].fillna(common_screen_size)

In [67]:
df.isnull().sum()

Unnamed: 0        0
Manufacturer      0
Category          0
Screen            0
GPU               0
OS                0
CPU_core          0
Screen_Size_cm    0
CPU_frequency     0
RAM_GB            0
Storage_GB_SSD    0
Weight_kg         0
Price             0
dtype: int64

In [72]:
df.dtypes

Unnamed: 0          int64
Manufacturer          str
Category            int64
Screen                str
GPU                 int64
OS                  int64
CPU_core            int64
Screen_Size_cm    float64
CPU_frequency     float64
RAM_GB              int64
Storage_GB_SSD      int64
Weight_kg         float64
Price               int64
dtype: object